CREATE OR REPLACE VIEW Lista_Uczniow AS
SELECT * From Uczniowie;

CREATE OR REPLACE VIEW Funkcje_Uczniow AS
SELECT UCZNIOWIE.IMIE_UCZEN, UCZNIOWIE.NAZWISKO_UCZEN, FUNKCJA.NAZWA_FUNKCJA
FROM UCZEN_FUNKCJA
JOIN FUNKCJA ON UCZEN_FUNKCJA.ID_FUNKCJA=FUNKCJA.ID_FUNKCJA
JOIN UCZNIOWIE ON UCZEN_FUNKCJA.ID_UCZEN = UCZNIOWIE.ID_UCZEN;


CREATE OR REPLACE FORCE EDITIONABLE VIEW "PROJEKT_OSWIECIMSKA_SPYTKOWSKA_GLOD"."KOMITET_SZKOLNY" ("IMIE_UCZEN", "NAZWISKO_UCZEN", "NAZWA_FUNKCJA") AS 
SELECT UCZNIOWIE.IMIE_UCZEN, UCZNIOWIE.NAZWISKO_UCZEN, FUNKCJA.NAZWA_FUNKCJA
FROM UCZEN_FUNKCJA
JOIN FUNKCJA ON UCZEN_FUNKCJA.ID_FUNKCJA=FUNKCJA.ID_FUNKCJA
JOIN UCZNIOWIE ON UCZEN_FUNKCJA.ID_UCZEN = UCZNIOWIE.ID_UCZEN
WHERE FUNKCJA.NAZWA_FUNKCJA = 'Członek komitetu szkolnego';


CREATE OR REPLACE FORCE EDITIONABLE VIEW "PROJEKT_OSWIECIMSKA_SPYTKOWSKA_GLOD"."SORTOWANIE_PO_SREDNIEJ" ("IMIE_UCZEN", "NAZWISKO_UCZEN", "SREDNIA") AS 
SELECT UCZNIOWIE.IMIE_UCZEN, UCZNIOWIE.NAZWISKO_UCZEN, SWIADECTWO.SREDNIA
FROM SWIADECTWO
JOIN UCZEN_KLASA ON SWIADECTWO.ID_UCZEN_KLASA = UCZEN_KLASA.ID_UCZEN_KLASA
JOIN UCZNIOWIE ON UCZEN_KLASA.ID_UCZEN = UCZNIOWIE.ID_UCZEN
ORDER BY SWIADECTWO.SREDNIA DESC;